### ISSUE TITLE
web3.net.getPeerCount TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jorisbontje** [cubedro/eth-net-intelligence-api#212]
```
2015-07-30 15:50 +00:00: /home/pi/eth-net-intelligence-api/lib/node.js:489
                                web3.net.getPeerCount(callback);
                                         ^
TypeError: undefined is not a function
    at Object.async.parallel.peers (/home/pi/eth-net-intelligence-api/lib/node.js:489:14)
    at /home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:583:25
    at /home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:124:9)
    at _parallel (/home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:582:20)
    at Object.async.parallel (/home/pi/eth-net-intelligence-api/node_modules/async/lib/async.js:598:9)
    at Node.getStats (/home/pi/eth-net-intelligence-api/lib/node.js:486:9)
    at Primus.<anonymous> (/home/pi/eth-net-intelligence-api/lib/node.js:241:8)
```

**Comment by jorisbontje** [comment]
fixed after `npm install`
