### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Georg243** [cubedro/eth-net-intelligence-api#232]
georg@georg-CELSIUS-W380:~/eth-net-intelligence-api$ sudo npm install
npm http GET http://registry.npmjs.org/web3/0.15.1
npm http 304 http://registry.npmjs.org/web3/0.15.1
npm http GET http://registry.npmjs.org/bignumber.js
npm http GET http://registry.npmjs.org/crypto-js
npm http GET http://registry.npmjs.org/utf8
npm http GET http://registry.npmjs.org/xmlhttprequest
npm http 304 http://registry.npmjs.org/bignumber.js
npm http 304 http://registry.npmjs.org/utf8
npm http 304 http://registry.npmjs.org/crypto-js
npm http 304 http://registry.npmjs.org/xmlhttprequest
npm ERR! Error: No compatible version found: bignumber.js@'debris/bignumber.js#master'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.1.0","1.1.1","1.2.0","1.2.1","1.3.0","1.4.0","1.4.1","1.5.0","2.0.0","2.0.1","2.0.2","2.0.3","2.0.5","2.0.6","2.0.7","2.0.8","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/georg/eth-net-intelligence-api
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/georg/eth-net-intelligence-api/npm-debug.log
npm ERR! not ok code 0

**Comment by mruaim** [comment]
sudo npm install -g npm
