### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by jorisbontje** [cubedro/eth-net-intelligence-api#233]
with version 5029c398d1b5deba1b14b6b187d76162a241acc1:

```
2016-02-20 15:07 +00:00: [eth] =✘= TypeError: object is not a function
    at Node.startWeb3Connection (/home/pi/eth-net-intelligence-api/lib/node.js:137:9)
    at new Node (/home/pi/eth-net-intelligence-api/lib/node.js:128:7)
    at Object.<anonymous> (/home/pi/eth-net-intelligence-api/app.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:28:21)
    at Module._compile (module.js:456:26)
```

**Comment by jorisbontje** [comment]
Oops, forgot to `npm update`
