### ISSUE TITLE
node type / version is blank when web3.eth.coinbase isn't set

### ISSUE THREAD

**Issue by cdetrio** [cubedro/eth-net-intelligence-api#245]
See the image:

![ethstats - node type version appears blank](https://cloud.githubusercontent.com/assets/997681/19601873/503b5670-97ab-11e6-9fdd-d26a2a3a5b11.png)

This is caused when web3.eth.coinbase is not set, since [node.js#L339](https://github.com/cubedro/eth-net-intelligence-api/blob/5d310fcdcdd628f597efaf112dfb99694d3e3226/lib/node.js#L339) will return an error:
```
> web3.eth.coinbase
etherbase address must be explicitly specified
    at web3.js:3119:20
    at web3.js:6023:15
    at get (web3.js:5923:38)
    at <anonymous>:1:-1
```

[PR #241](https://github.com/cubedro/eth-net-intelligence-api/pull/241) fixes this bug.

**Comment by gaiazov** [comment]
+1 it is annoying to have to set coinbase on nodes
