### ISSUE TITLE
progrem run Error

### ISSUE THREAD

**Issue by woyinzf** [cubedro/eth-net-intelligence-api#251]
at Object.<anonymous> (/Users/yinzf/Documents/shiji__workspace/nodejs_workspace/eth-net-intelligence-api/lib/node.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
	2017-07-18 11:54 +08:00: [eth] =✘= Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by woyinzf** [comment]
The above error is in the mac environment,But linux can be displayed properly

**Comment by mikeyb** [comment]
`2017-07-18 11:54 +08:00: [eth] =✘= Error: Cannot find module 'web3'`
