### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by MysticRyuujin** [cubedro/eth-net-intelligence-api#254]
My `node-app-err-0.log` is throwing these errors:

```
2018-01-30 10:05 -08:00: Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/bin/www/lib/utils/logger.js:4:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

I'm on Ubuntu 16.04.3 x64 and I just pulled from git

I tried to run `npm install chalk -g` and it completed successfully but it didn't make a difference...

**Comment by MysticRyuujin** [comment]
Nevermind I forgot `npm install`
